# Generated by Django 6.0.5 on 2026-06-02 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contacto@festival-luciernagas.mx', max_length=254, verbose_name='correo de contacto')),
                ('telefono', models.CharField(default='+52 (55) 5512 3456', max_length=40, verbose_name='teléfono')),
                ('horario', models.CharField(default='Lun – Vie · 09:00 – 18:00 hrs', max_length=120, verbose_name='horario')),
                ('instagram', models.CharField(blank=True, default='@Festival_LuciernagasMx', max_length=120, verbose_name='Instagram')),
                ('web', models.CharField(blank=True, default='festival-luciernagas.mx', max_length=120, verbose_name='Sitio web')),
                ('twitter', models.CharField(blank=True, default='@fila_oficial', max_length=120, verbose_name='Twitter / X')),
                ('youtube', models.CharField(blank=True, default='@FestivalLuciernagas', max_length=120, verbose_name='YouTube')),
                ('mensaje_soporte', models.TextField(default='Si necesitas ayuda con tu reservación o tienes preguntas sobre el Festival Internacional de las Luciérnagas, escríbenos a contacto@festival-luciernagas.mx. Te responderemos en un máximo de 24 horas hábiles.', verbose_name='mensaje de soporte')),
                ('fechas_festival', models.CharField(default='12 Jun — 18 Ago 2026', max_length=80, verbose_name='fechas del festival')),
                ('num_parques', models.PositiveSmallIntegerField(default=6, verbose_name='número de parques')),
            ],
            options={
                'verbose_name': 'información de contacto',
                'verbose_name_plural': 'información de contacto',
            },
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('Cabaña', 'Cabaña'), ('Camping', 'Camping')], default='Cabaña', max_length=20, verbose_name='tipo')),
                ('precio', models.PositiveIntegerField(default=0, verbose_name='precio por noche')),
                ('capacidad_personas', models.PositiveSmallIntegerField(default=4, verbose_name='capacidad por hospedaje')),
                ('capacidad_cabanas', models.PositiveSmallIntegerField(default=0, verbose_name='cupo de cabañas')),
                ('capacidad_camping', models.PositiveSmallIntegerField(default=0, verbose_name='cupo de zonas de camping')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, verbose_name='calificación')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('lat', models.FloatField(default=19.46, verbose_name='latitud')),
                ('lng', models.FloatField(default=-98.55, verbose_name='longitud')),
                ('carpeta_imagenes', models.CharField(help_text='Nombre de la carpeta en static/core/assets/parks/', max_length=80, verbose_name='carpeta de imágenes')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('ultima_edicion', models.DateTimeField(auto_now=True, verbose_name='última edición')),
            ],
            options={
                'verbose_name': 'parque',
                'verbose_name_plural': 'parques',
                'ordering': ['-rating', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='amenidad')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenidades', to='core.parque')),
            ],
            options={
                'verbose_name': 'amenidad',
                'verbose_name_plural': 'amenidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nombre', models.CharField(max_length=120, verbose_name='autor')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='calificación')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('verificada', models.BooleanField(default=True, verbose_name='verificada')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.parque')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reseña',
                'verbose_name_plural': 'reseñas',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=24, unique=True, verbose_name='folio')),
                ('tipo_hospedaje', models.CharField(default='Cabaña', max_length=20, verbose_name='tipo de hospedaje')),
                ('fecha_entrada', models.DateField(verbose_name='entrada')),
                ('fecha_salida', models.DateField(verbose_name='salida')),
                ('noches', models.PositiveSmallIntegerField(default=1, verbose_name='noches')),
                ('personas', models.PositiveSmallIntegerField(default=1, verbose_name='personas')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='subtotal')),
                ('servicio', models.PositiveIntegerField(default=0, verbose_name='servicio')),
                ('impuestos', models.PositiveIntegerField(default=0, verbose_name='impuestos')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='total')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=12, verbose_name='estado')),
                ('metodo_pago_marca', models.CharField(blank=True, default='Visa', max_length=20, verbose_name='marca de tarjeta')),
                ('metodo_pago_last4', models.CharField(blank=True, max_length=4, verbose_name='últimos 4 dígitos')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='core.parque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reservación',
                'verbose_name_plural': 'reservaciones',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('estado', models.CharField(choices=[('available', 'Disponible'), ('low', 'Disponibilidad baja'), ('full', 'Lleno'), ('blocked', 'Bloqueado (mantenimiento)')], default='available', max_length=12, verbose_name='estado')),
                ('cupo_cabanas', models.PositiveSmallIntegerField(default=0, verbose_name='cupo de cabañas')),
                ('cupo_camping', models.PositiveSmallIntegerField(default=0, verbose_name='cupo de zonas de camping')),
                ('reservadas_cabanas', models.PositiveSmallIntegerField(default=0, verbose_name='cabañas reservadas')),
                ('reservadas_camping', models.PositiveSmallIntegerField(default=0, verbose_name='zonas reservadas')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='core.parque')),
            ],
            options={
                'verbose_name': 'disponibilidad',
                'verbose_name_plural': 'disponibilidades',
                'ordering': ['fecha'],
                'unique_together': {('parque', 'fecha')},
            },
        ),
    ]
